version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
